function [  DimNames, ClassNames, ClassCount, ...
            DimCount, FileCount, Data, ChannelDict, ObsPerFile ] = ...
            loadEMGData( DataDir, DataColumnNames, UseManualChannelSelections )
    
    % CONSTANTS
    DimCount = size( DataColumnNames,2 );
    ObsPerFile = 2640;
    
    % LOAD DATA
    Data = spreadsheetDatastore( DataDir, 'IncludeSubfolders', true );
    Data.SelectedVariableNames = DataColumnNames;  
    FileCount = length( Data.Files ); 

    % BUILD DICT OF SPECIFIC CHANNELS TO USE FOR EACH GESTURE - DETERMINED
    % THROUGH MANUAL REVIEW OF THE TIME-SERIES PLOTS
    Keys = { 'IndexFinger','ElbowFlex','Pinky',...
                'WristOut','RingFinger','MiddleFinger',...
                'Rest', 'Thumb' };
    if UseManualChannelSelections == 1
        Values = {...
            { 'CH4', 'CH5' }...
            ,{ 'CH1','CH5' }...
            ,{ 'CH1', 'CH4' }...
            ,{ 'CH1', 'CH2', 'CH5' }...
            ,{ 'CH7' }...
            ,{ 'CH1', 'CH2', 'CH4', 'CH7' }...
            ,{ 'CH1','CH2','CH4','CH5','CH6','CH7' }...
            ,{ 'CH1', 'CH4', 'CH5', 'CH6' }
        };
    else
        Values = {...
            { 'CH1','CH2','CH4','CH5','CH6','CH7' }...
            ,{ 'CH1','CH2','CH4','CH5','CH6','CH7' }...
            ,{ 'CH1','CH2','CH4','CH5','CH6','CH7' }...
            ,{ 'CH1','CH2','CH4','CH5','CH6','CH7' }...
            ,{ 'CH1','CH2','CH4','CH5','CH6','CH7' }...
            ,{ 'CH1','CH2','CH4','CH5','CH6','CH7' }...
            ,{ 'CH1','CH2','CH4','CH5','CH6','CH7' }...
            ,{ 'CH1','CH2','CH4','CH5','CH6','CH7' }...
        };
    end
    ChannelDict = containers.Map( Keys, Values );

    % PREPROCESS
    ClassNames = strings( FileCount, 1 );   % store all the class names
    for iFile = 1 : FileCount

        % GET CLASS NAME
        FilePath = Data.Files{ iFile };
        [ FullFilePath, FileName, Ext ] = fileparts( FilePath );
        FileNameCellArray = strsplit( FileName, '_' );
        ClassName = FileNameCellArray{ 2 };
        ClassNames( iFile, 1 ) = ClassName;

    end
    DimNames = unique( DataColumnNames );
    ClassCount=size( unique( ClassNames ), 1 );
    
end







